# Simple preprocessing


Hello People! 

Welcome to the first Notebook. 

Like we described in our presentation. This is notebook is used for the creation of easy features. 

__What is an easy feature?__

You can think of it like a column in one of the data files. At the beginning
we have the three input files (items, info, orders). In the end we will export 2 files: 
- ```dynamic_features.pkl```-> All time dependent data such as date features (e.g day_of_month)
- ```static_features.pkl```-> All static features such as itemID and so on

After this notebook we **only** work with ```dynamic_features.pkl``` and ```static_features.pkl```.

_Why the fuck ```*.pkl```?!_ 

pkl in this case stands for 'pickle' and allows us to very space efficiently safe the data in bytes. When loading the data we don't have the problem with delimiters like we would have with csv. But most important: Later we need to save models and so on with pickle. So we already start here using it to have some consistency in these unconsistent times :D

__How do we handle our test set ?__
As we already tried out in team 1, it is crucial to think about the complexity of test features beforehand. Therefore, we now prepare the test set from right the beginning. 

This means that we now already created rows for the testset. This means the aforementioned files then consist out of **all** the data (test + validation + train). _But why?!_ In the first two notebooks we have function (later more about those) to mutate our data. These mutation then directly can be done for test and train set, using the same functions. This finally leads to correct function. Furthermore, everyone who is adding a new feature now already needs to think about, how it may be applied to the train set (in which we have not all information)

How the creation of testset features works, will be elaborated later. 

__What is the structure of this notebook?__

1. **Setting up Colab**
1. **Notes and Ideas**
1. **Setting up Notebook**
1. **Create Dynamic_Features Dataframe** 
1. **Deviation of Promotions and Creation of Test Set**
1. **Defining Feature Functions**
1. **Applying Features**
1. **Testset Mappings**
1. **Saving data**

__TL;DR__
- Input = info.csv/ items.csv / orders.csv
- Output = dynamic_features.csv / static_features.csv
- Notebook for easy features (new Columns in source data)
- Test set is simulated and created already here.

# 1. Setting up Colab

Here we set up colab. U knooow it :D 

In case u don't use colab, please specify the variable ```use_colab``` to false. In case u don't use it its unavoidable to make sure that noone changed something online while u change it offline. The results of this would be worse than a division by zero.

In [1]:
use_colab: bool = True

In case u accidentall run the following code twice u will get following weird and confusing error:

```
OSError: [Errno 107] Transport endpoint is not connected
```

In this case just restart the runtime above.

In [2]:
if use_colab:
  import os
  from google.colab import drive 
  drive.mount("/content/gdrive", force_remount=True)
  # Change directory for nicer imports
  %cd "/content/gdrive/My Drive/Data_Mining_Cup/05 Code/"

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive
/content/gdrive/My Drive/Data_Mining_Cup/05 Code

# 2. Notes and Ideas

## Ideas for new Features
Please specify assignment in bold and brackets behind. If nobody is assigned put the "To Be Assigned (TBA)" flag. 

- Boolean two days after promotion (Nic)
- how rare are solds **(TBA)**
- Sum of solds 14 days after -> Can be used for the direct prediction of sum of values **(TBA)**

## Notes

Currently no notes :(

# 3. Setting up Notebook

Here we setup some parameters for the notebook to work in the expected ways.

If we want to **use the final test phase** for the later submission, we need to specify the following parameter **```make_final_submission``` to true.** Otherwise the selfmade test set will be used.

In [3]:
make_final_submission: bool = False

In case we don't want to make a final submission, we now have to specify the test_set. In case you change it, please leave a comment on why and what the new one is. If the end is defined as None we use all the data from start_period (inclusive) till the end of dataset. 

In case make_final_submission is True we do not use those parameters.

In [4]:
# This will set the start of test period to 2 weeks before end of data
test_period_start: str="2018-06-02"
# Use till the end
test_period_end: str="2018-06-15"

In [5]:
# These datapoints are for the final submision
final_submission_start: str="2018-06-30"
final_submission_end: str="2018-07-13"  # shouldn't it be 07-13 if inclusive?

#### Imports

Here you can add imports u need. Please use alphabetical order to not import new stuff twice.

In [6]:
from datetime import datetime, timedelta

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from typing import List, Callable

%matplotlib inline

### Data Imports

Now we import the source data. In case we use our test set, we delete the test set values to simulate later submission.

In [7]:
# In tables 'infos' and 'items' itemID is used as index
info = pd.read_csv('/content/gdrive/My Drive/Data_Mining_Cup/02 Data/DMC20_Data/infos.csv', delimiter='|', index_col="itemID")
items = pd.read_csv('/content/gdrive/My Drive/Data_Mining_Cup/02 Data/DMC20_Data/items.csv', delimiter='|', index_col="itemID")

In [8]:
orders = pd.read_csv('/content/gdrive/My Drive/Data_Mining_Cup/02 Data/DMC20_Data/orders.csv', delimiter='|', parse_dates=True)
orders['time'] = pd.to_datetime(orders['time'])

# 4. Create DataFrame ```dynamic_features```
Here we create the data frame for dynamic features out of the orders dataframe. Following the orders dataframe can only be used to add something to this dataframe. 
As indexes it has the date as well as the itemID.

In [ ]:
orders['date'] = orders['time'].dt.date
dynamic_feature = orders.groupby(['itemID','date']).aggregate({'order':'sum', 'salesPrice':'mean'})

In [ ]:
test = dynamic_feature.reset_index()

In [ ]:
itemID_list = test['itemID'].unique()

In [ ]:
itemID_list

array([    1,     2,     3, ..., 10460, 10462, 10463])

In [ ]:
# Create a new dataframe to store time-dependent data for items
_begin = min(orders['time']).date()
_end = max(orders['time']).date()
timespan = [p.date().strftime('%Y%m%d') for p in pd.date_range(start=_begin, end=_end)]
idx=  pd.MultiIndex.from_product([items.index, pd.to_datetime(timespan)], names=['itemID', 'date'])

In [ ]:
dynamic_feature = pd.DataFrame(dynamic_feature, index=idx)
dynamic_feature['order'] = dynamic_feature['order'].fillna(0)
dynamic_feature['salesPrice'] = dynamic_feature['salesPrice'].groupby('itemID').apply(lambda group: group.fillna(items.loc[group.name].recommendedRetailPrice))

# using the following forward & backward fill method would cause wrong prices (changed to the above line instead)
# e.g. itemID 58 was never sold thus not appeared in the orders table, then it would get the price from itemID 57 
# dynamic_feature['salesPrice'] = dynamic_feature['salesPrice'].fillna(method="bfill")
# dynamic_feature['salesPrice'] = dynamic_feature['salesPrice'].fillna(method="ffill")

# 5. Deviation of Promotions and Creation of Test Set

Here we derive the promotions using the following method. This needs to be done to be able to have promotions in the test set when we manipulate it.

#### Promotion Derivation Functions

The following functions can be used for deriving the promotions for test set. However, these function can also be used later to derive promotions for train set.

In [ ]:
def add_promotions_via_log2_new(lam=1, limit=2.5, **kwargs)->pd.DataFrame:
  """
  data = timedep
  Predicts when items were promoted according to number of sold items on a daily
  basis.
  As promotions are marked all days where the follwing holds:
  log2((sold_on_current_day + lambda) / (sold_on_prev_day + lambda)) > limit
  """
  def promotion_function(data: pd.DataFrame, ors: pd.DataFrame=None):
    print("... adding promotions")
    sold_shifted = data['order'].shift(periods=1)
    trend = np.log2((data['order'] + lam) / (sold_shifted + lam))
    data['promoted'] = trend > limit
    print(f"..... There are {sum(data['promoted'])} promotions derived")
    return data
  return promotion_function

In [ ]:
# OLD FUNCTION
def add_promotions_via_log2(data: pd.DataFrame, ors: pd.DataFrame, lam=1, **kwargs)->dict:
  """
  data = timedep
  Predicts when items were promoted according to number of sold items on a daily
  basis.
  As promotions are marked all days where the follwing holds:
  log2((sold_on_current_day + lambda) / (sold_on_prev_day + lambda)) > limit
  """
  print("... adding promotions")
  # Add the timestamp as index
  ors = ors.set_index(pd.DatetimeIndex(ors['time']))

  # Hyperparameter for smoothing
  idx = None

  grouped = ors.groupby(['itemID'])
  for item_id, group in grouped:
    if item_id % 500 == 0:
      print(f"   ... {item_id}/{len(grouped)}")
    sold_each_day = group['order'].resample('D').sum()
    first_day = sold_each_day.index[0]

    if first_day.day == 1 and first_day.month == 1:
      # This is the first day of the simulation, the day before is unknown
      fill_value = np.nan
    else:
      # The item was not bought on the day before
      fill_value = 0
    
    # Use log difference (see https://www.youtube.com/watch?v=_N88aMUjDb8&feature=youtu.be, ~8m15s)
    # Shift for one day
    sold_each_day_shifted = sold_each_day.shift(periods=1, fill_value=fill_value)

    trend = np.log2((sold_each_day + lam) / (sold_each_day_shifted + lam))

    promoted = trend[trend > 2.5]
    promoted_dates = list(map(lambda x: x.to_pydatetime().strftime('%Y%m%d'), promoted.index))

    _idx = pd.MultiIndex.from_product([[item_id], promoted_dates])
    if idx is None:
      idx = _idx
    else:
      idx = idx.union(_idx)
  
  data.loc[idx, 'promoted'] = True
  # data.fillna(value={'promoted': False}, inplace=True)
  data['promoted'].fillna(False, inplace=True)

  return data

In [ ]:
def add_promotions_via_naive_mean_deviation(data, **kwargs):
  data["avg"] = data["order"].mean()
  data["promotion2"] = 0
  data.loc[data["avg"]< data["order"],"promotion2"] = 1
  data.drop(columns=['avg'], inplace = True)
  return data

### Apply Promotion Derivation

The following parameter defines which function is used to derive the promotions:

In [ ]:
function_for_promotion: Callable = add_promotions_via_log2_new(limit=2.5)

---
Now we are adding the promotions to all of the data

In [ ]:
dynamic_feature = function_for_promotion(data=dynamic_feature)

... adding promotions
..... There are 17596 promotions derived

#### Add Testing Columns

Here we are also saving the orders which should be predicted. These are needed to check the performance of trained models.

In [ ]:
if make_final_submission:
  # Set test range
  test_range =  pd.date_range(start=final_submission_start, end=final_submission_end)
  # Create index for test
  idx = pd.MultiIndex.from_product([items.index, pd.to_datetime(test_range)], names=['itemID', 'date'])
  # Create DataFrame for the ending
  dynamic_feature_test = pd.DataFrame(index=idx, columns=dynamic_feature.columns)

  # Add the simulation price
  simulation_price2 = pd.DataFrame(info['simulationPrice'].rename('salesPrice'))
  # Add simulation Price
  dynamic_feature_test = dynamic_feature_test.drop('salesPrice', axis=1).join(pd.DataFrame(simulation_price2), on='itemID')
  dynamic_feature_test['promoted'] = False
  
  # Add promotions
  for idx, row in info.iterrows():
    if not(str(row['promotion'])=="nan"):
      promotions = row['promotion'].split(",")
      for date in promotions:
        dynamic_feature_test.loc[(idx, pd.to_datetime(date)),'promoted']=True
    
else:
  #test_range = pd.date_range(start=test_period_start, end=test_period_end)
  dynamic_feature_test = dynamic_feature[dynamic_feature.index.get_level_values(1) >= pd.to_datetime(test_period_start)]
  dynamic_feature = dynamic_feature[dynamic_feature.index.get_level_values(1) < pd.to_datetime(test_period_start)]
  simulation_price = pd.DataFrame(dynamic_feature_test['salesPrice'].groupby('itemID').mean())
  dynamic_feature_test = dynamic_feature_test.drop('salesPrice', axis=1).join(pd.DataFrame(simulation_price), on='itemID')
  
  # Save the testing orders 
  dynamic_feature_test.to_pickle("./data/orders_for_test.pkl")
  

  # Delete Order in test set
  dynamic_feature_test['order'] = np.NaN

dynamic_feature = dynamic_feature.append(dynamic_feature_test)

del dynamic_feature_test

In [ ]:
dynamic_feature

                   order  salesPrice  promoted
itemID date
1      2018-01-01    0.0        3.11     False
       2018-01-02    0.0        3.11     False
       2018-01-03    0.0        3.11     False
       2018-01-04    0.0        3.11     False
       2018-01-05    0.0        3.11     False
...                  ...         ...       ...
10463  2018-06-25    NaN      282.16     False
       2018-06-26    NaN      282.16     False
       2018-06-27    NaN      282.16     False
       2018-06-28    NaN      282.16     False
       2018-06-29    NaN      282.16     False

[1883340 rows x 3 columns]

In the ```orders``` dataframe, we are not able to get information for prediction, because in later submission we don't neither. Therefore we need to delete rows, which define rows in the later notebook.

In [ ]:
if not make_final_submission:
    orders = orders[orders['time'] < test_period_start]

# 6. Defining Feature Functions

In this area new features can be defined. A feature function takes the data as argument and returns the mutated dataframe. Following attributes can be used additionally:

- ```ors```: The orders dataframe
- ```its```: The items dataframe

__Why do we need functions?__

This has three main reasons:
- We can easily add and delete functions
- We have an overview on which features are used currently
- The features we create here can be used in other projects as well 

__What if my function needs additional parameters?__

Then create a function which returns a the final function. The following function returns a function which changes the sales price to the default value + 10.

```
def test_function(default_value=1):

  def final_function(data: pd.DataFrame):
    data['salesPrice'] = default_value + 10

    return data
  return final_function

```
Later this function can be triggered using following:

```
test_function(default_value=10)(data)
```
This structure is important for later and enables adding the same feature with only different parameter.

__How do I import features which are created by other regressors models or whatever?__

Then please save the feature column in a seperate file. Then import the column in a function and then add it to the data like in the other feature function. In case that u simply import a file, specify how this feature is created, and please give a link or description on the location of the source code of the creation of this file. 
Furthermore, please only import files, which are accessible by all of the team. So that in the end every team member is able to add the feature and run all of the pipeline.

#### Has Rating Ordinal Feature

Adds True if there is a rating.

In [ ]:
def add_has_rating_feature(data: dict, **kwargs)->dict:
  """
  Ordinal feature, which returns if a method has a rating
  """
  print("... applying has rating")
  data['has_rating'] = data['customerRating']> 0
  return data

#### Summed orders per item

Feature which describes, how much was brought 2 weeks after this day. This feature can then be used for predicting the whole simulation period.

In [ ]:
# dynamic_feature['order'].iloc[i]

In [ ]:
#####
# UNDER CONSTRUCTION
# -- probably won't use 
###

# def summed_order_in_item(time_steps=14):
  
#   def feature_function(data,**kwargs):
#     test = data['order'].rolling(time_steps).sum()
#     return test
#   return feature_function


# this function is not applied at the very end, do we still want to use it?
# the number could be wrong as it's not grouped by each item 
# also need to fill NaN values at the very beginning for the rolling time_steps

In [ ]:
#summed_order_in_item()(data=dynamic_feature)

#### Add Divided Time Feature

Adds time information:
- Timestamp
- Time
- Date
- Hour
- Day_of_year
- Day_of_month
- Month
- Week_nr
- Day_of_Week

In [ ]:
def add_divided_time_feature(data: dict, **kwargs)->dict:
  """
  data = dynamic_feature

  Divides the timestamp of the data into different features like the weekday etc.
  """
  print("... adding time features")

  date = data.index.get_level_values(1)

  data['day_of_year'] = date.dayofyear
  data['day_of_month'] = date.day
  data['month'] = date.month
  data['week_nr'] = date.week # updated here, week_nr should be int instead of str
  data['day_of_week'] = date.dayofweek # int(Monday:0 Sunday:6)
  return data

#### Aggregate Sold Feature

Adds daily_sold, weekly_sold and monthly_sold items

In [ ]:
def add_aggregated_sold_feature(data:dict, **kwargs)->dict: 
  print('... applying sold features')
  # add sold per day/week/month column to orders
  data = data.assign(daily_sold = data.groupby(['date', 'itemID']).order.transform('sum'))
  data = data.assign(weekly_sold = data.groupby(['week_nr', 'itemID']).order.transform('sum'))
  data = data.assign(monthly_sold = data.groupby(['month', 'itemID']).order.transform('sum'))
  return data

####Add_avg_salesPrice
Adds the average salesprice over the whole training and validation_period

TODO: Check if not also test period is within -> If this is the case, its not tragic cause we use the sim_price for sales price in testing

In [ ]:
def add_avg_salesPrice(data, ors, **kwargs):
  """
  data = its
  Calculates the avg sales price over the whole training and validation period
  """
  print("... adding avg sales price")

  # Calculate average over all orders (non-unique)
  avg_salesPrice_nonunique = ors[['salesPrice', 'itemID']].groupby('itemID').mean().rename(columns={'salesPrice':'avg_salesPrice_nonunique'})
  data = data.join(avg_salesPrice_nonunique, on="itemID")
  data['avg_salesPrice_nonunique'].fillna(data['recommendedRetailPrice'], inplace=True)
  return data

#### Add Avg Daily Sales Price

Adds the daily sales price for each item

In [ ]:
def add_avg_daily_salesPrice(data, ors, its, **kwargs):
  """
  data = timedep
  Calculates the average of (unique) prices for every day.
  """
  print("... adding daily sales price")

  grouped = ors.groupby(['itemID', 'date'])['salesPrice']

  # Add average of unique prices
  daily_price_item = grouped.unique().apply(lambda x: np.mean(x))
  data.loc[daily_price_item.index, 'avg_daily_salesPrice'] = daily_price_item

  # Add average of all prices (non-unique)
  daily_price_item_nonunique = grouped.mean()
  data.loc[daily_price_item_nonunique.index, 'avg_daily_salesPrice_nonunique'] = daily_price_item_nonunique

  # If value is missing, first check if there is average of the whole period. -> would not be null 
  data['avg_daily_salesPrice'] = data['avg_daily_salesPrice'].groupby('itemID').apply(lambda group: group.fillna(its.loc[group.name].avg_salesPrice_nonunique))
  data['avg_daily_salesPrice_nonunique'] = data['avg_daily_salesPrice_nonunique'].groupby('itemID').apply(lambda group: group.fillna(its.loc[group.name].avg_salesPrice_nonunique))

  return data

#### Add Avg of daily salesPrice
Calculate average over daily averages.

In [ ]:
def add_avg_of_daily_salesPrice(data, td, **kwargs):
  """
  data = items
  Calculate average over daily averages (nonunique)
  """
  avg = td.groupby('itemID')['avg_daily_salesPrice_nonunique'].mean()
  data.loc[avg.index, 'avg_salesPrice'] = avg
  return data

#### Add Avg Daily Sold
  data = items
  
  Calculate avg daily sold and standard deviation.

In [ ]:
def add_avg_daily_sold(data, ors, **kwargs):
  """
  data = items
  Calculate avg daily sold and standard deviation.

  """
  print("... adding avg daily sold")
  nr_days_training = (ors['time'].max() - ors['time'].min()).days + 1
  daily_sold = ors.groupby(['itemID', 'date']).order.sum()
  grouped = daily_sold.groupby('itemID')

  # Avg over all training period
  avg_sold_item = (grouped.sum() / nr_days_training)
  data.loc[avg_sold_item.index, 'avg_sold_day'] = avg_sold_item

  # Avg over days where total number of orders > 0
  avg_sold_item_only_nonzero = grouped.mean()
  data.loc[avg_sold_item_only_nonzero.index, 'avg_sold_day_only_nonzero'] = avg_sold_item_only_nonzero
  
  # Std over days where total number of orders > 0
  std_sold_item_only_nonzero = grouped.std()
  data.loc[std_sold_item_only_nonzero.index, 'std_sold_day_only_nonzero'] = std_sold_item_only_nonzero

  # Fill missing values
  data['avg_sold_day'].fillna(0, inplace=True)
  data['avg_sold_day_only_nonzero'].fillna(0, inplace=True)
  data['std_sold_day_only_nonzero'].fillna(0, inplace=True)
  return data

#### Add_SalesPrice_Over_Price
TODO: Please add description and assertions for wrong order (Just test if add_avg_daily_salesPrice_nonunique & add_avg_salesPrice are present, if not tell that the other functions need to be executed before)

TODO: The function which should be executed, are not existing!

@ Markus, the function for creating avg_daily_salesPrice_nonunique indeed does exist (check out function add_avg_daily_salesPrice()), also avg_salesPrice should also be created within the function add_avg_of_daily_salesPrice(). avg_salesPrice should be the average of avg_daily_salesPrice_nonunique. I hope it makes sense (Min).

In [ ]:
# Execute after: def add_avg_of_daily_salesPrice & add_avg_of_daily_salesPrice

# I added "salesPrice_over_avg_salesPrice" and "salesPrice_over_avg_salesPrice_nonunique" (Min)

def add_salesPrice_over_price(data, its, **kwargs):
  """
  data = timedep or dynamic features
  calculate relationships between price of that day and [recommendedRetailPrice, avg_salesPrice, and avg_salesPrice_nonunique]
  """
  print("... applying add_salesPrice_over_price")

  df_sales = data.join(its, on = 'itemID', how = 'left')
  data['salesPrice_over_recommended'] = df_sales['avg_daily_salesPrice_nonunique'] / df_sales['recommendedRetailPrice']
  data['salesPrice_over_avg_salesPrice'] = df_sales['avg_daily_salesPrice_nonunique'] / df_sales['avg_salesPrice']
  data['salesPrice_over_avg_salesPrice_nonunique'] = df_sales['avg_daily_salesPrice_nonunique'] / df_sales['avg_salesPrice_nonunique']
  
  data['salesPrice_over_recommended'].fillna(0, inplace=True)
  data['salesPrice_over_avg_salesPrice'].fillna(0, inplace=True)
  data['salesPrice_over_avg_salesPrice_nonunique'].fillna(0, inplace = True)

  return data

#### Add German holidays

Method to add German Holidays

In [ ]:
def add_german_holidays(data, **kwargs):
  
  import holidays
  print("... applying add_german_holidays")
  de_holidays = holidays.DE(years= 2018) #Holidays Library
  a = pd.DataFrame(de_holidays.keys())

  # Creating bool: if date is holiday
  data['de_holidays'] = data.index.get_level_values(1).isin(a)

  return data

#### Add Has Promotion on Day

Adds a column to orders that tells whether the item in this row has been 
  promoted on that day.

In [ ]:
def add_has_promotion_on_day(data: dict, its: dict, **kwargs):
  """
  Adds a column to orders that tells whether the item in this row has been 
  promoted on that day.
  """
  print("... applying add_has_promotion_on_day")
  data = data.assign(has_promotions_this_day=False)
  grouped = data.groupby(['itemID', 'date'])
  for (item_id, date), group in grouped:
    date_correct_format = group.iloc[0]['time'].to_pydatetime().strftime('%Y-%m-%d')
    if date_correct_format in its.loc[item_id].promotion_derived.split(','):
      data.loc[group.index, ['has_promotions_this_day']] = True
  return data

## Num Promotions

In [ ]:
def num_promotions(data, td, its, **kwargs):
  print("... adding num promotions")
  num_promotions = td[td['promoted']==True].groupby('itemID')['promoted'].count()
  num_promotions.name = 'num_promotions'
  data = data.join(num_promotions, rsuffix="_num_promotions")
  data['num_promotions'].fillna(value=0,inplace=True)
  return data

## Promotion in Data

In [ ]:
# add after num_promotions
def promotion_in_data(data, td, its, **kwargs):
  print("... adding promotion in data")
  print(td)
  data['promotion_in_data'] = data['num_promotions'].astype('bool')
  return data

## Avg Sold Promoted

In [ ]:
def avg_sold_promoted(data, td, its, **kwargs):
  print("... adding avg_sold_promoted")
  promoted = td[td['promoted']==True].groupby('itemID')['order'].mean()
  promoted.name = 'avg_sold_promoted'
  data = data.join(promoted, rsuffix="_promoted")
  data['avg_sold_promoted'].fillna(value=data['avg_sold_promoted'].mean(),inplace=True)
  return data

## Avg Sold Not Promoted

In [ ]:
def avg_sold_not_promoted(data, td, its, **kwargs):
  print("... adding avg_sold_not_promoted")
  not_promoted = td[td['promoted']==False].groupby('itemID')['order'].mean()
  not_promoted.name = 'avg_sold_not_promoted'
  data = data.join(not_promoted)
  data['avg_sold_not_promoted'].fillna(value=data['avg_sold_not_promoted'].mean(),inplace=True)
  return data

## Last promotions

In [ ]:
def last_promotion(item, avg_sales_of_all_items):
  itemID = item.index.values[0][0]
  if itemID % 1000 == 0:
    print(itemID)

  first_day_of_data = item.index.get_level_values(1).to_list()[0]
  last_day_of_data = item.index.get_level_values(1).to_list()[-1]

  def get_avg_order_on_promo_day(promos):
    idx = pd.MultiIndex.from_product([[itemID], promos])
    orders_all = item.loc[idx]
    orders = orders_all[orders_all.order.notna()].order
    if len(orders) > 0:
      avg = orders.mean()
    else:
      avg = avg_sales_of_all_items
    return round(avg)

  def helper(start_date, end_date, default_sales=None):
    # Set values to entries between start_date and end_date
    days_between = (end_date - start_date).days
    first_day_to_set = start_date + timedelta(days=1)  # First day after last promotion

    if first_day_to_set < first_day_of_data:
      value_for_january_1st = (first_day_of_data - first_day_to_set).days + 1
      first_day_to_set = first_day_of_data
      days_since_last_promo = np.arange(value_for_january_1st, days_between+1)
      last_promo_sales = default_sales  # Avg of promotions for this item
    else:
      days_since_last_promo = np.arange(1, days_between+1)  # A list of increasing numbers, starting with 1
      last_promo_sales = item.loc[(itemID, start_date)].order  # Sales on the last promoted day

    item.loc[(itemID, first_day_to_set):(itemID, end_date), "days_since_last_promotion"] = days_since_last_promo    
    item.loc[(itemID, first_day_to_set):(itemID, end_date), "last_promoted_sales"] = last_promo_sales
    return item

  # Get list of dates when the item was promoted
  promotions = item.index[item.promoted].get_level_values(1).to_list()

  default_sales = get_avg_order_on_promo_day(promotions)

  last_promo = datetime(year=2017, month=12, day=1)  # First imaginary promotion

  if len(promotions) == 0:
    item = helper(last_promo, last_day_of_data, default_sales)
    return item

  for promo_day in promotions:
    # Loop through all promotions and set all intermediate values at once
    item = helper(last_promo, promo_day, default_sales)
    last_promo = promo_day

  # Add values for the days after the last promotion
  
  if (last_day_of_data - last_promo).days > 0:
    helper(last_promo, last_day_of_data)

  return item

In [ ]:
def last_promotions(data, **kwargs):
  print("... adding last_promotions")
  data["days_since_last_promotion"] = np.nan
  data["last_promoted_sales"] = np.nan
  avg_sales_of_all_items = data[data['promoted']==True].groupby('itemID')['order'].mean().mean()
  data = data.groupby('itemID').apply(last_promotion, avg_sales_of_all_items = avg_sales_of_all_items)
  return data

## Creating Price Clusters

Creation of price buckets

In [ ]:
# for recommendedRetailprice in items
def add_price_bins(n_bins: int, field: str):
  def bin_fct(data, **kwargs):
    print(f"... applying price bins on {field} with {n_bins} bins")
    data[f'{field}_bucket'] = pd.qcut(data[field], n_bins, labels=range(0, n_bins))
    return data
  return bin_fct

## Creating Price/Order Clusters

In [ ]:
# Using sum of all orders per item
def add_price_sumOrder_cluster(data, ors, **kwargs):
  # implement number of orders from order file 
  sold_each_item = ors[['itemID', 'order']].groupby(['itemID']).sum()
  data = data.reset_index()
  data = data.join(sold_each_item, on="itemID")
  # Clustering
  n_bins = 3
  data['priceCluster'] = pd.qcut(data.recommendedRetailPrice, n_bins, labels=range(0, n_bins))
  data['orderCluster'] = pd.qcut(data.order, n_bins, labels=range(0, n_bins))
  # drop all rows with NaN in orderCluster  
  data = data[data['orderCluster'].notna()]
  
  # Combining price and order Cluster
  def combi_pr_or(row):
      global val
      if row['priceCluster'] == 0 and row['orderCluster'] == 0:
          val = 1 #cheap and sold rarely
      elif row['priceCluster'] == 0 and row['orderCluster'] == 1:
          val = 2 #cheap and sold middle
      elif row['priceCluster'] == 0 and row['orderCluster'] == 2:
          val = 3 #cheap and sold often
      elif row['priceCluster'] == 1 and row['orderCluster'] == 0:
          val = 4 #middle price and sold rarely
      elif row['priceCluster'] == 1 and row['orderCluster'] == 1:
          val = 5 #middle price and sold middle
      elif row['priceCluster'] == 1 and row['orderCluster'] == 2:
          val = 6 #middle price and sold often
      elif row['priceCluster'] == 2 and row['orderCluster'] == 0:
          val = 7 #expensive and sold rarely
      elif row['priceCluster'] == 2 and row['orderCluster'] == 1:
          val = 8 #expensive and sold middle
      elif row['priceCluster'] == 2 and row['orderCluster'] == 2:
          val = 9 #expensive and sold often
      return val

  # Combine both Cluster with combi_pr_or function
  data['price_sumSales_cluster'] = data.apply(combi_pr_or, axis=1)
  data = data.drop(['priceCluster', 'orderCluster', 'order'], axis=1)
  data = data.set_index("itemID")

  return data

In [ ]:
# Using max of Order per item
def add_price_maxOrder_cluster(data, ors, **kwargs):
  # find max order for every itemID in save as order in max_orders
  max_orders = ors.loc[ors.reset_index().groupby(['itemID'])['order'].idxmax()]
  data = data.reset_index()
  data = pd.merge(data, max_orders[['order', 'itemID']], on="itemID", how='left')
  # Clustering
  n_bins = 3
  data['priceCluster'] = pd.qcut(data.recommendedRetailPrice, n_bins, labels=range(0, n_bins))
  data['orderCluster'] = pd.qcut(data.order, n_bins+1, labels=range(0, n_bins), duplicates='drop')
  
  # drop all rows with NaN in orderCluster  
  data = data[data['orderCluster'].notna()]

  # Combining price and order Cluster
  def combi_pr_or(row):
      global val
      if row['priceCluster'] == 0 and row['orderCluster'] == 0:
          val = 1 #cheap and sold rarely
      elif row['priceCluster'] == 0 and row['orderCluster'] == 1:
          val = 2 #cheap and sold middle
      elif row['priceCluster'] == 0 and row['orderCluster'] == 2:
          val = 3 #cheap and sold often
      elif row['priceCluster'] == 1 and row['orderCluster'] == 0:
          val = 4 #middle price and sold rarely
      elif row['priceCluster'] == 1 and row['orderCluster'] == 1:
          val = 5 #middle price and sold middle
      elif row['priceCluster'] == 1 and row['orderCluster'] == 2:
          val = 6 #middle price and sold often
      elif row['priceCluster'] == 2 and row['orderCluster'] == 0:
          val = 7 #expensive and sold rarely
      elif row['priceCluster'] == 2 and row['orderCluster'] == 1:
          val = 8 #expensive and sold middle
      elif row['priceCluster'] == 2 and row['orderCluster'] == 2:
          val = 9 #expensive and sold often
      return val
    
  # Combine both Cluster with combi_pr_or function
  data['price_maxSales_cluster'] = data.apply(combi_pr_or, axis=1)
  data = data.drop(['priceCluster', 'orderCluster', 'order'], axis=1)
  data = data.set_index("itemID")

  return data

#### Clusters for items that were frequently bought together

In [ ]:
def add_bought_together_clusters(data, **kwargs):
  """
  data = items

  Items that were "often" bought together are in the same cluster.
  What "often" means can be changed in the nb linked below. The clusters that 
  are currently used are based on parameters (10, 40): 
  - two items must be bought together at least 40 times.
  - at least 10 percentiles of times when one item was bought, the other item 
    was also bought.
  (the described approach is similar to apriori algorithm)

  I made the relation transitive: if A together with B and B together with C,
  then A together with C, which means that all three (A, B, C) are in the same 
  cluster.

  Cluster value -1 means no cluster (the item was rarely or never bought 
  together with something else).

  Link to the nb where this is derived: https://colab.research.google.com/drive/1L0LEBlxD-X9wvyH28XQNvQTmQDq68sYl
  """
  print("... adding bought_together_cluster")
  clusters = pd.read_pickle('./data/bought_together.pk')
  data['bought_together_cluster'] = clusters['together_10_40']
  return data

In [ ]:
def add_two_days_after_promo(data, **kwargs):
  """
  add boolean variable for if date is one or two days after promo, as after an auction items stay promoted for 44 hours
  """
  data.reset_index(inplace=True)
  data.set_index('itemID', inplace = True)
  data["promotion_lag1"] = data.groupby(data.index).promoted.shift(1)
  data["promotion_lag2"] = data.groupby(data.index).promoted.shift(2)
  data["promotion_lag1"].fillna(False, inplace = True)
  data["promotion_lag2"].fillna(False, inplace = True)
  data["two_days_after_promo"] = data["promotion_lag1"]
  data.loc[data["promotion_lag2"]==True,"two_days_after_promo"] = True
  data.reset_index(inplace=True)
  data.set_index(["itemID","date"],inplace=True)

  return data

In [ ]:
'''def add_total_sales_and_promos(data, **kwargs):
  """
  Add function for total sales and total promotions per day
  """
  data2 = data.reset_index(drop=True)
  data2 = data.groupby(["date"]).agg({'order': 'sum','promoted': 'sum'})
  data2.rename(columns = {'order':'total_sales','promoted':'count_promotions'})
  data = data.merge(data2, on='date',how='left')
  
  return data'''

'def add_total_sales_and_promos(data, **kwargs):\n  """\n  Add function for total sales and total promotions per day\n  """\n  data2 = data.reset_index(drop=True)\n  data2 = data.groupby(["date"]).agg({\'order\': \'sum\',\'promoted\': \'sum\'})\n  data2.rename(columns = {\'order\':\'total_sales\',\'promoted\':\'count_promotions\'})\n  data = data.merge(data2, on=\'date\',how=\'left\')\n  \n  return data'

In [ ]:
def add_total_sales_and_promos(data, **kwargs):
  """
  Add function for total sales and total promotions per day
  """
  data2 = data.reset_index()
  data2 = data2[['date', 'order', 'promoted']]
  data2 = data2.groupby(["date"]).sum()
  data2 = data2.rename(columns = {'order':'total_sales','promoted':'count_promotions'})
  
  data = data.reset_index()
  data = data.join(data2, on='date',how='left')
  data = data.set_index(["itemID","date"])
  return data

In [ ]:
add_total_sales_and_promos(dynamic_feature)

                   order  salesPrice  promoted  total_sales  count_promotions
itemID date
1      2018-01-01    0.0        3.11     False       6305.0              36.0
       2018-01-02    0.0        3.11     False       6165.0              46.0
       2018-01-03    0.0        3.11     False       2821.0              24.0
       2018-01-04    0.0        3.11     False      10819.0              54.0
       2018-01-05    0.0        3.11     False      11465.0              41.0
...                  ...         ...       ...          ...               ...
10463  2018-06-25    NaN      282.16     False          0.0             110.0
       2018-06-26    NaN      282.16     False          0.0             172.0
       2018-06-27    NaN      282.16     False          0.0             140.0
       2018-06-28    NaN      282.16     False          0.0             119.0
       2018-06-29    NaN      282.16     False          0.0             162.0

[1883340 rows x 5 columns]

In [ ]:
def forecast_total_sales(data, **kwargs):
  """
  forecast total sales for simulation period using prophet
  """
  #Prepare format for prophet
  data2 = data.reset_index(drop=True)
  data2 = data.groupby(["date"]).agg({'order': 'sum','promoted': 'sum'})
  data2.reset_index(inplace=True)
  data2.rename(columns = {'date':'ds','order':'y','promoted':'count_promotions'}, inplace = True) 

  #Prepare train and test data
  train = data2[:-14]
  test = data2[-14:]

  #Make Prediction
  from fbprophet import Prophet
  prophet_basic = Prophet()
  prophet_basic.add_regressor('count_promotions')
  prophet_basic.fit(train)
  forecast = prophet_basic.predict(test)

  #Add Forecast to original data
  data = data.reset_index()
  forecast['y'] = forecast['yhat']
  final_data = train.append(forecast[['ds','y','count_promotions']])
  final_data.rename(columns= {'ds':'date','y':'total_sales'}, inplace = True)
  data = data.merge(final_data, on='date',how='left')
  data.set_index(['itemID','date'], inplace = True)
  #data.drop(columns = ['level_0','index'], inplace = True)
  return data

# 7. Apply Features

Now here we can add the function which should be applied.
The function in the list, is executed in exactly this order. In case of a keyError it might be that one function is dependend on another function which is not yet executed.

## Apply Function on Dynamic Features

Here the function which should be applied on the 'dynamic features' dataframe are specified.

In [ ]:
applied_features_for_dynamic_features = [
                    add_divided_time_feature,
                    add_two_days_after_promo, 
                    add_total_sales_and_promos,
                    ## forecast_total_sales, #only for final submission
                    # add_avg_daily_salesPrice, # add directly before applying dynamic features list, due to dependency with some static features
                    ### add_sold_per_period, # this fct doesn't exist? # Here order will be filled with nan -> Not good we need orders for test set to be Nan. -> This fct doesn't exists?
                    add_german_holidays,
                    # add_salesPrice_over_price, # add directly before applying dynamic features list, due to dependency with some static features
                    last_promotions,
                    add_price_bins(10, field='salesPrice')
]

## Apply Function on Items Table

In [ ]:
applied_features_for_items = [
                    add_price_sumOrder_cluster,
                    add_price_maxOrder_cluster,
                    # add_avg_salesPrice, # add directly before applying dynamic features, see next code cell
                    add_has_rating_feature,
                    add_price_bins(10,field='recommendedRetailPrice'),
                    ## add_avg_daily_sold,
                    add_bought_together_clusters,
                    # add_avg_of_daily_salesPrice, # add directly before applying dynamic features, see next code cell
                    num_promotions, 
                    promotion_in_data,
                    avg_sold_promoted,
                    ### avg_sold_not_promoted # columns overlap but no suffix specified: Index(['avg_sold_not_promoted'], dtype='object') in final_submission
]

## Technical Applying the features
This is the code to really use the above features.

In [ ]:
# dependent features, need to run in this order.. 
# apply first before calling the lists 

items = add_avg_salesPrice(items, orders)

... adding avg sales price

In [ ]:
dynamic_feature = add_avg_daily_salesPrice(dynamic_feature, orders, items)

... adding daily sales price

In [ ]:
items = add_avg_of_daily_salesPrice(items, dynamic_feature)
dynamic_feature = add_salesPrice_over_price(dynamic_feature, items)

... applying add_salesPrice_over_price

In [ ]:
def apply_features_training(data:dict, features: List[Callable])->dict:
  assert isinstance(features, list)

  backup_data = data.copy()
  
  try:
    for feature in features:
      result = feature(data, ors=orders, its=items, td=dynamic_feature)
      assert result is not None, "The function need to return the mutated data"
      data = result
    return data
  except Exception as e:
    print(f"\nERROR:\nIn Function {feature} was following Error:\n\n {e} \n Now reverting the data")
    return backup_data

print("+++ ADDING DYNAMIC FEATURES+++ \n _____________________________________________")
dynamic_feature = apply_features_training(dynamic_feature, applied_features_for_dynamic_features)
print("+++ ADDING STATIC FEATURES+++ \n _____________________________________________")
items = apply_features_training(items, applied_features_for_items)

assert dynamic_feature['order'].isnull().values.any()

+++ ADDING DYNAMIC FEATURES+++
 _____________________________________________
... adding time features
... applying add_german_holidays
... adding last_promotions
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
... applying price bins on salesPrice with 10 bins
+++ ADDING STATIC FEATURES+++
 _____________________________________________
... applying has rating
... applying price bins on recommendedRetailPrice with 10 bins
... adding bought_together_cluster
... adding num promotions
... adding promotion in data
                   order  salesPrice  ...  last_promoted_sales  salesPrice_bucket
itemID date                           ...
1      2018-01-01    0.0        3.11  ...                164.0                  0
       2018-01-02    0.0        3.11  ...                164.0                  0
       2018-01-03    0.0        3.11  ...                164.0                  0
       2018-01-04    0.0        3.11  ...                164.0                  0
       2018-01-05    0.0        3.11  ...                164.0                  0
...                  ...         ...  ...                  ...                ...
10463  2018-06-25    NaN      282.16  ...                146.0                  9
       2018-06-26    NaN      282.16  ...                146.0                  9
       2018-06-27    NaN      282.16  ...                146.0                  9
       2018-06-28    NaN      282.16  ...                146.0                  9
       2018-06-29    NaN      282.16  ...                146.0                  9

[1883340 rows x 22 columns]
... adding avg_sold_promoted

In [ ]:
dynamic_feature

                   order  salesPrice  ...  last_promoted_sales  salesPrice_bucket
itemID date                           ...
1      2018-01-01    0.0        3.11  ...                164.0                  0
       2018-01-02    0.0        3.11  ...                164.0                  0
       2018-01-03    0.0        3.11  ...                164.0                  0
       2018-01-04    0.0        3.11  ...                164.0                  0
       2018-01-05    0.0        3.11  ...                164.0                  0
...                  ...         ...  ...                  ...                ...
10463  2018-06-25    NaN      282.16  ...                146.0                  9
       2018-06-26    NaN      282.16  ...                146.0                  9
       2018-06-27    NaN      282.16  ...                146.0                  9
       2018-06-28    NaN      282.16  ...                146.0                  9
       2018-06-29    NaN      282.16  ...                146.0                  9

[1883340 rows x 22 columns]

In [ ]:
#print("+++ ADDING STATIC FEATURES+++ \n _____________________________________________")
#items = apply_features_training(items, applied_features_for_items)

In [ ]:
#Here all values from 1 to 9 should exist
items.price_maxSales_cluster.value_counts()

In [ ]:
# Here I will still apply the automated features (using featuretools) 
# once all new features are created correctly in the static/items table (Min)
# this will build upon the features we created in items as well as the original orders table 
# the newly created features will be added to "static_features_final.pk"

# Save dataset
Here the both datasets are saved.

The following variable is used to save the data

In [ ]:
# save_folder = "./data"

Following both datasets are saved. Please don't save other data from here. We are only using the two files as described above.

In [ ]:
# def save_data(df: pd.DataFrame, filename: str):
#   """
#   Saves data to the pickle file.
#   Sample call:
#   save_data(items, "items.pk")
#   """
#   filename = f"{save_folder}/{filename}"
#   df.to_pickle(filename)


# save_data(items, 'static_features_final.pk' if make_final_submission else 'static_features.pk')
# save_data(dynamic_feature, 'dynamic_features_final.pk' if make_final_submission else 'dynamic_features.pk')

# FINAL DATA
These are the finalized dataframes

## Static Features

In [ ]:
items

        brand  manufacturer  ...  promotion_in_data  avg_sold_promoted
itemID                       ...
1           0             1  ...               True         164.500000
2           0             2  ...              False         135.892729
3           0             3  ...               True          63.639457
4           0             2  ...               True          27.505000
5           0             2  ...               True          81.500000
...       ...           ...  ...                ...                ...
10431     180           128  ...               True         228.843333
10459     180           253  ...              False         135.892729
10460       0           253  ...              False         135.892729
10462     180           253  ...              False         135.892729
10463       0           253  ...              False         135.892729

[8385 rows x 17 columns]

## Dynamic Features

In [ ]:
dynamic_feature

                    order  salesPrice  ...  last_promoted_sales  salesPrice_bucket
itemID date                            ...
1      2018-01-01    0.00        3.11  ...                164.0                  0
       2018-01-02    0.00        3.11  ...                164.0                  0
       2018-01-03    0.00        3.11  ...                164.0                  0
       2018-01-04    0.00        3.11  ...                164.0                  0
       2018-01-05    0.00        3.11  ...                164.0                  0
...                   ...         ...  ...                  ...                ...
10463  2018-06-25  282.16      282.16  ...                130.0                  9
       2018-06-26  282.16      282.16  ...                130.0                  9
       2018-06-27  282.16      282.16  ...                130.0                  9
       2018-06-28  282.16      282.16  ...                130.0                  9
       2018-06-29  282.16      282.16  ...                130.0                  9

[1883340 rows x 22 columns]

In [ ]:
items.price_maxSales_cluster.value_counts()

7    2433
4    1468
3    1259
2     796
1     744
5     735
6     588
8     219
9     143
Name: price_maxSales_cluster, dtype: int64

In [ ]:
# !pip install featuretools

In [ ]:
import featuretools as ft

In [ ]:
entity_set = ft.EntitySet(id = 'itemID')

# create itemID as a column for featuretools 
items['itemID'] = items.index 

# create entity "items"
entity_set = entity_set.entity_from_dataframe(entity_id = 'items', 
                                              dataframe = items, 
                                              variable_types = {'brand': ft.variable_types.Categorical,
                                                                'manufacturer': ft.variable_types.Categorical,
                                                                'category1': ft.variable_types.Categorical,
                                                                'category2': ft.variable_types.Categorical,
                                                                'category3': ft.variable_types.Categorical},
                                              index = 'itemID') 

# create entity from the orders, with index "orderID" as no unique index exists
entity_set = entity_set.entity_from_dataframe(
                              entity_id = 'orders', 
                              dataframe = orders,
                              make_index = True,  # when unique index does not exist
                              index = 'orderID')
                              # time_index = 'time')

# Relationship: items - parent; orders - children
r_items_orders = ft.Relationship(entity_set['items']['itemID'], entity_set['orders']['itemID'])

# Add the relationship to the entity set
entity_set = entity_set.add_relationship(r_items_orders)

In [ ]:
# apply dfs or Deep Feature Synthesis: using basic building blocks (feature primitives) -> form new features. 
# The depth of a "deep feature" is equal to the number of stacked primitives.

static_features, static_features_names = ft.dfs(entityset=entity_set, target_entity='items', max_depth = 2)

# keep relevant features 
cols = [c for c in static_features.columns if ("transactID" not in c) and ("YEAR" not in c)]

static_features = static_features[cols]

In [ ]:
static_features

        customerRating  ...  MODE(orders.WEEKDAY(date))
itemID                  ...
1                 4.38  ...                           0
2                 3.00  ...                           1
3                 5.00  ...                           3
4                 4.44  ...                           6
5                 2.33  ...                           1
...                ...  ...                         ...
10431             5.00  ...                           0
10459             0.00  ...                           5
10460             0.00  ...                           0
10462             0.00  ...                           6
10463             0.00  ...                           4

[8385 rows x 42 columns]

In [15]:
dynamic_testing = pd.read_pickle('./data/dynamic_features_final_nb2_2906_one_hot_ws7.pk')

In [16]:
dynamic_testing.reset_index(inplace = True)

In [62]:
dynamic_testing

         itemID       date  order  ...  order_t-5  order_t-6  order_t-7
0             1 2018-01-01    0.0  ...        NaN        NaN        NaN
1             1 2018-01-02    0.0  ...        NaN        NaN        NaN
2             1 2018-01-03    0.0  ...        NaN        NaN        NaN
3             1 2018-01-04    0.0  ...        NaN        NaN        NaN
4             1 2018-01-05    0.0  ...        NaN        NaN        NaN
...         ...        ...    ...  ...        ...        ...        ...
2029817   10463 2018-07-09    NaN  ...        NaN        NaN        NaN
2029818   10463 2018-07-10    NaN  ...        NaN        NaN        NaN
2029819   10463 2018-07-11    NaN  ...        NaN        NaN        NaN
2029820   10463 2018-07-12    NaN  ...        NaN        NaN        NaN
2029821   10463 2018-07-13    NaN  ...        NaN        NaN        NaN

[2029822 rows x 44 columns]

In [19]:
promotions = dynamic_testing[(dynamic_testing['date'] > "2018-06-29") & (dynamic_testing['date'] < "2018-07-14")]

In [20]:
promotions[promotions["promoted"] == 1]

         itemID       date  order  ...  order_t-5  order_t-6  order_t-7
1883703      26 2018-07-13    NaN  ...        NaN        NaN        NaN
1883717      27 2018-07-13    NaN  ...        NaN        NaN        NaN
1883745      29 2018-07-13    NaN  ...        NaN        NaN        NaN
1883817      35 2018-07-01    NaN  ...        0.0        0.0        0.0
1883818      35 2018-07-02    NaN  ...        0.0        0.0        0.0
...         ...        ...    ...  ...        ...        ...        ...
2029594   10447 2018-07-10    NaN  ...        NaN        NaN        NaN
2029608   10448 2018-07-10    NaN  ...        NaN        NaN        NaN
2029636   10450 2018-07-10    NaN  ...        NaN        NaN        NaN
2029707   10455 2018-07-11    NaN  ...        NaN        NaN        NaN
2029735   10457 2018-07-11    NaN  ...        NaN        NaN        NaN

[2066 rows x 44 columns]

In [32]:
promotions[promotions["itemID"] == 81]

         itemID       date  order  ...  order_t-5  order_t-6  order_t-7
1884460      81 2018-06-30    NaN  ...        0.0        0.0        1.0
1884461      81 2018-07-01    NaN  ...        0.0        0.0        0.0
1884462      81 2018-07-02    NaN  ...        0.0        0.0        0.0
1884463      81 2018-07-03    NaN  ...        0.0        0.0        0.0
1884464      81 2018-07-04    NaN  ...        0.0        0.0        0.0
1884465      81 2018-07-05    NaN  ...        NaN        0.0        0.0
1884466      81 2018-07-06    NaN  ...        NaN        NaN        0.0
1884467      81 2018-07-07    NaN  ...        NaN        NaN        NaN
1884468      81 2018-07-08    NaN  ...        NaN        NaN        NaN
1884469      81 2018-07-09    NaN  ...        NaN        NaN        NaN
1884470      81 2018-07-10    NaN  ...        NaN        NaN        NaN
1884471      81 2018-07-11    NaN  ...        NaN        NaN        NaN
1884472      81 2018-07-12    NaN  ...        NaN        NaN        NaN
1884473      81 2018-07-13    NaN  ...        NaN        NaN        NaN

[14 rows x 44 columns]

In [42]:
info_promotions = info[~info['promotion'].isnull()]

info_promotions

        simulationPrice                         promotion
itemID
26                14.27                        2018-07-13
27                 1.64                        2018-07-13
29                56.13                        2018-07-13
35               337.84  2018-07-01,2018-07-02,2018-07-13
58               277.72                        2018-07-13
...                 ...                               ...
10447             44.99                        2018-07-10
10448             63.00                        2018-07-10
10450             44.43                        2018-07-10
10455             62.84                        2018-07-11
10457             22.71                        2018-07-11

[1843 rows x 2 columns]

In [46]:
list_date = []

for index, row in info_promotions.iterrows():
    list_date.append(row["promotion"].split(","))
    # print(row["promotion"].split(","))

In [48]:
flat_date_list = [item for sublist in list_date for item in sublist]

In [50]:
len(flat_date_list)

2066

In [35]:
info[info.index == 81]

        simulationPrice promotion
itemID
81               102.21       NaN

In [61]:
promotions[promotions["itemID"] == 276]

         itemID       date  order  ...  order_t-5  order_t-6  order_t-7
1887190     276 2018-06-30    NaN  ...        0.0        0.0        0.0
1887191     276 2018-07-01    NaN  ...        0.0        0.0        0.0
1887192     276 2018-07-02    NaN  ...        0.0        0.0        0.0
1887193     276 2018-07-03    NaN  ...        0.0        0.0        0.0
1887194     276 2018-07-04    NaN  ...        0.0        0.0        0.0
1887195     276 2018-07-05    NaN  ...        NaN        0.0        0.0
1887196     276 2018-07-06    NaN  ...        NaN        NaN        0.0
1887197     276 2018-07-07    NaN  ...        NaN        NaN        NaN
1887198     276 2018-07-08    NaN  ...        NaN        NaN        NaN
1887199     276 2018-07-09    NaN  ...        NaN        NaN        NaN
1887200     276 2018-07-10    NaN  ...        NaN        NaN        NaN
1887201     276 2018-07-11    NaN  ...        NaN        NaN        NaN
1887202     276 2018-07-12    NaN  ...        NaN        NaN        NaN
1887203     276 2018-07-13    NaN  ...        NaN        NaN        NaN

[14 rows x 44 columns]

In [60]:
info_promotions[info_promotions.index == 10060]

Empty DataFrame
Columns: [simulationPrice, promotion]
Index: []

In [56]:
info[info.index == 81]

        simulationPrice promotion
itemID
81               102.21       NaN

In [57]:
static_testing = pd.read_pickle('./data/static_features_final_nb2_2906_one_hot_ws7.pk')

In [59]:
static_testing[static_testing.index == 81]

        customerRating  ...  bought_together_cluster__55
itemID                  ...
81                 5.0  ...                            0

[1 rows x 664 columns]

In [72]:
info[info.index == 359]

        simulationPrice   promotion
itemID
359               33.53  2018-06-30